WordPress/theme-experiments

- CONTRIBUTING.md
Starting with a minimal set of guidelines for now, but it may be nice to include some suggestions as to what kinds of contributions could be interesting.
> Add a starting point for a contributor's document

- README.md
Let's discuss what information would be useful to include in the README of this repository.
I put a few ideas in there, open to everyone's suggestions.
> Adding details to the README

- twentynineteen-blocks/block-template-parts/header.html
- twentynineteen-blocks/style.css
**Description**
Follows #4 and adds social links to the TwentyNineteen block based theme.
https://github.com/WordPress/theme-experiments/pull/4#issuecomment-576418857
> Adding styles and markup for social links in the header

- twentytwenty-blocks/block-template-parts/footer.html
- twentytwenty-blocks/block-template-parts/header.html
**Description**
This PR adds a jump-link in the footer that brings scrolls the window to the top of the page. 
**Testing Instructions**
- Clone and install the theme
- Visit any page, click on the jump link in the footer
- Validate that it brings you to the top of the page
> Footer jump link

- gutenberg-starter-theme-blocks/block-template-parts/header.html
- gutenberg-starter-theme-blocks/css/blocks.css
- gutenberg-starter-theme-blocks/experimental-theme.json
- gutenberg-starter-theme-blocks/functions.php
- gutenberg-starter-theme-blocks/style.css
This PR adds basic Global Styles rules to Gutenberg Starter Theme Blocks, as per the [new documentation](https://developer.wordpress.org/block-editor/developers/themes/theme-json/).
> Gutenberg Starter Theme Blocks: Try adding new Global Styles Rules

- magazine-example/experimental-theme.json
Fix the theme.json to generate root variables.
> Refactor global styles theme.json

- README.md
This PR updates the readme with a table listing of the themes and the version they were last tested against.
> Update README.md with What's Here

- twentytwentyone-blocks/block-templates/page.html
Both posts and pages must support comments.
> TT1: Add comments to pages.

- twentytwentyone-blocks/block-templates/front-page.html
- twentytwentyone-blocks/block-templates/index.html
- twentytwentyone-blocks/block-templates/page.html
- twentytwentyone-blocks/block-templates/single.html
Replaces the div of the header template part with `<header>` and adds the .site-header class.
Replaces the div of the footer template part with `<footer>` and adds the .site-footer class.
> TT1: Update footer and header tags and add CSS classes

- twentytwentyone-blocks/block-template-parts/footer.html
Fixes #85.
Before|After
---|---
> Twenty Twenty-One Blocks: Add footer content

- emptytheme/README.md
Now that #81 has been merged, it could use a quick readme. I think this covers the basics.
> Add a readme for the emptytheme

- twentytwentyone-blocks/style.css
> Fix alignment rules

- tt1-blocks/block-templates/404.html
- tt1-blocks/block-templates/index.html
- tt1-blocks/block-templates/page-home.html
- tt1-blocks/block-templates/page.html
- tt1-blocks/block-templates/single.html
Removes the theme attributes from template parts, only for TT1 Blocks.
> TT1 Blocks, remove theme attribute

- tt1-blocks/block-template-parts/header.html
Possible fix for https://github.com/WordPress/theme-experiments/issues/214
> TT1 Blocks: Use a placeholder for the primary navigation

- tt1-blocks/experimental-theme.json
Remove the duplicate "core/site-title".
> Remove duplicate site title from theme.json

- emptytheme/README.md
A while back we added a `singular.html` template to the `emptytheme`. This just updates the readme to acknowledge it.
> Mention the singular template in the emptytheme readme.

- tt1-blocks/README.md
- tt1-blocks/assets/css/blocks.css
- tt1-blocks/block-templates/index.html
- tt1-blocks/block-templates/single.html
- tt1-blocks/functions.php
- tt1-blocks/inc/block-patterns.php
- tt1-blocks/inc/block-styles.php
- tt1-blocks/index.php
- tt1-blocks/readme.txt
- tt1-blocks/style.css
- tt1-blocks/theme.json
> Various updates to TT1 Blocks

- fse-tutorial/block-template-parts/footer.html
- fse-tutorial/block-template-parts/header.html
- fse-tutorial/block-templates/index.html
- fse-tutorial/block-templates/page.html
- fse-tutorial/block-templates/single.html
- fse-tutorial/functions.php
- fse-tutorial/style.css
- fse-tutorial/theme.json
For https://github.com/WordPress/gutenberg/pull/31269
> Add a basic theme for the create a block theme tutorial

- tt1-blocks/readme.txt
- tt1-blocks/style.css
> TT1 Blocks: Bump the version up to 0.4.7

- emptytheme/style.css
> Change Theme Name to Emptytheme

- tt1-blocks/readme.txt
- tt1-blocks/style.css
This version will fix the issues of the query-loop to post-template.
> Maintain changelog and readme file
