WordPress/theme-experiments

twentynineteen-blocks/functions.php, twentytwenty-blocks/functions.php
**Description**
Removes trailing commas in a `join` statement which throw syntax errors below php 7.3.
This PR addresses #10. 
**How to Test**
Run 'functions.php' through a php linter and ensure no errors are found
=> Fix PHP syntax errors in #10

gutenberg-starter-theme-blocks/block-templates/index.html, gutenberg-starter-theme-blocks/block-templates/page-blog.html
The `<header>`, `<main>`, and `<footer>` elements inside of block-template files render as broken classic blocks in the experimental Site Editor. This PR changes those to use group blocks instead, which improves a user's ability to use that screen. This unfortunately loses those semantic tags, but it seems like the more appropriate thing to do until Gutenberg provides a way to create more semantic full-page markup natively. 
---
**Before**
**After**
=> [Gutenberg Starter Theme] Remove non-gutenberg HTML in block template files

twentynineteen-blocks/block-templates/index.html, twentynineteen-blocks/style.css
(Same as #14, but for the Twenty Nineteen theme variant)
The `<header>`, `<main>`, and `<footer>` elements inside of block-template files render as broken classic blocks in the experimental Site Editor. This PR changes those to use group blocks instead, which improves a user's ability to use that screen. This unfortunately loses those semantic tags, but it seems like the more appropriate thing to do until Gutenberg provides a way to create more semantic full-page markup natively.
---
**Before**
**After**
=> [Twenty Nineteen Blocks] Remove non-gutenberg HTML in block template files

twentynineteen-blocks/block-templates/singular.html, twentynineteen-blocks/style.css
This PR tries to add a home page showing the list of posts to the 2019 theme using the recent posts block.
=> Add a home page template using the latest posts block to 2019

parisienne/block-templates/index.html, parisienne/functions.php
Following the lead of #14 and #15 (and #16). The `<header>`, `<main>`, and `<footer>` elements inside of block-template files render as broken classic blocks in the experimental Site Editor. This PR changes those to use group blocks instead, which improves a user's ability to use that screen.
This PR also removes an unused function at the end of `functions.php`, and tidies up some spacing in there too.
=> [Parisienne] Remove non-gutenberg HTML in block template files

twentytwenty-blocks/block-templates/index.html, twentytwenty-blocks/style.css
Following the lead of #14 and #15. The `<header>`, `<main>`, and `<footer>` elements inside of block-template files render as broken classic blocks in the experimental Site Editor. This PR changes those to use group blocks instead, which improves a user's ability to use that screen.
---
Before:
After:
=> [Twenty Twenty Blocks] Remove non-gutenberg HTML in block template files

twentynineteen-blocks/block-templates/singular.html, twentynineteen-blocks/style.css
This PR adds the recent core/post-comments block to the singular template of 2019-blocks.
The design is not exactly the same as 2019 because it uses the default comments template. 
Potentially, we could add a "comments.php" template to the theme and the block would pick it.
=> add the post comments block to 2019

twentytwenty-blocks/functions.php
This should fix deprecations notices like
```
Deprecated: register_pattern is deprecated since version Gutenberg 8.1.0! Use register_block_pattern() instead. in /var/www/html/wp-includes/functions.php on line 4726
```
that I'm currently getting in Site Editing when using an up-to-date Gutenberg git clone with this repo :slightly_smiling_face: 
Context for deprecation:
https://github.com/WordPress/gutenberg/issues/21655
https://github.com/WordPress/gutenberg/pull/21970
https://github.com/WordPress/gutenberg/pull/22177
https://github.com/WordPress/gutenberg/pull/22341
Pinging @melchoyce @kjellr @jffng @youknowriad for review :slightly_smiling_face:
=> Use register_block_pattern() instead of deprecated register_pattern()

gutenberg-starter-theme-blocks/css/blocks.css
=> [Gutenberg Starter Theme Blocks] Missing and wrong commas in blocks.css

require-gutenberg/README.md, require-gutenberg/require-gutenberg.php
A simple implementation using admin-notices to allow FSE themes to require Gutenberg as a plugin.
The code can be copy-pasted inside a theme directly.
=> Add implementation to require Gutenberg in FSE themes.

gutenberg-starter-theme-blocks/block-template-parts/header.html
The site title and navigation blocks now allow for center-alignment. This updates the header template part to reflect that. 
Before
After
=> Gutenberg Starter Theme Blocks: Center align site title and menu

gutenberg-starter-theme-blocks/functions.php, twentynineteen-blocks/functions.php, twentytwenty-blocks/functions.php
Adds theme support for `custom-line-height` and `experimental-link-color` to twentynineteen-blocks and twentytwenty-blocks since these now require the theme to opt-in.  This will be helpful for development and testing purposes of the site editor, fse blocks, etc.  I assume we would want these added @youknowriad / @kjellr ?  However, I am unsure about the other themes in the repo so have only added them here for now.
=> Add line-height and link-color support for 2020/2019-blocks themes.

twentytwenty-blocks/functions.php, twentytwenty-blocks/twentytwenty-styles/editor-style-block.css
Followup to #44. @jffng pointed out that `editor-style-block.css` uses the `.editor-styles-wrapper` class throughout it. This is a remnant from the original Twenty Twenty Theme, where the stylesheet was [pulled in](https://core.trac.wordpress.org/browser/trunk/src/wp-content/themes/twentytwenty/functions.php#L391) via the `enqueue_block_editor_assets` hook instead of the usual `add_editor_style`. Since we use `add_editor_style` in the blocks-based version, those `editor-styles-wrapper` classes should be prepended automatically, and are not necessary to use in the stylesheet anymore. 
To test: Compare editor styles on `master` to this branch, and make sure they look and work the same.
=> Twenty Twenty Blocks: Remove entry-styles-wrapper classes from editor-style-block.css

gutenberg-starter-theme-blocks/block-template-parts/footer.html, gutenberg-starter-theme-blocks/block-template-parts/header.html, gutenberg-starter-theme-blocks/block-templates/index.html, gutenberg-starter-theme-blocks/block-templates/single.html, gutenberg-starter-theme-blocks/css/blocks.css
While writing https://github.com/WordPress/gutenberg-starter-theme/pull/104, I noticed that some of the templates here in the Gutenberg Starter Theme Blocks could use some udpates. This PR includes a few changes: 
- It updates the tagline and footer text colors to match the usual theme colors (I wonder if this should map to what's in `experimental-theme.json` though. 🤔)
- It adjusts the spacing of the header to better match the usual layout. 
- It uses the query block rather than the latest posts block to show single posts. 
- It moves the single post view to a `single.html` template instead of the `index.html` template.
- It changes some CSS to allow for alignments to work as expected in the query block.
=> Update Gutenberg Starter Theme Blocks templates

twentytwentyone-blocks/assets/css/blocks.css, twentytwentyone-blocks/experimental-theme.json, twentytwentyone-blocks/functions.php
This PR takes care of a handful of minor notes from @jorgefilipecosta and @carolinan on the original PR: 
- Removes unnecessary title tag theme support. ([Reference](https://github.com/WordPress/theme-experiments/pull/57/files#r514006754))
- Removes the customFontSize opt-in from theme.json (since this is on by default). ([Reference](https://github.com/WordPress/theme-experiments/pull/57/files#r514260804))
- Moves the site title font size rule to theme.json. ([Reference](https://github.com/WordPress/theme-experiments/pull/57/files#r513731870))
- Removes an unnecessary set of theme.json rules for the paragraph block. These can just be inherited from the global rules. ([Reference](https://github.com/WordPress/theme-experiments/pull/57/files#r513741949))
None of these should have any visual …
=> Twenty Twenty-One Blocks: Minor cleanup

twentytwentyone-blocks/block-templates/page.html, twentytwentyone-blocks/block-templates/single.html
Fixes #60.
Note that this is dependent on https://github.com/WordPress/gutenberg/pull/26601: The post title block doesn't support wide alignment yet, but it should. 
To test, view a single post/page template in the site editor and on the front end. 
Before|After
---|---
=> Twenty Twenty-One Blocks: Update page header design

twentytwentyone-blocks/assets/css/blocks.css
Closes #61. 
This migrates the last of the custom block style CSS over from the original version of Twenty Twenty-One. 
- Latest Posts: Dividers
- Latest Posts: Borders
- Editor styles for Social Links: Dark gray color
=> Twenty Twenty-One Blocks: Add missing block style CSS

twentytwentyone-blocks/experimental-theme.json
This PR adds font size names to 2021 blocks theme. This change makes the font size picker render the font size names currently everything appears as white space.
=> Add: Font size names to 2021 blocks

README.md, twentytwentyone-blocks/README.md
Updates the readme to remove the need for folks to check the "Full site editing" experiment, since this is [handled automatically](https://make.wordpress.org/core/2020/11/04/whats-new-in-gutenberg-4-november/) as of Gutenberg 9.3. 
Also removes the unzipping/re-zipping step, since https://github.com/WordPress/gutenberg/pull/26391 has been merged.
=> TT1: Update installation instructions to sync up with Gutenberg 9.3

twentytwentyone-blocks/experimental-theme.json
This PR adds a set of font-family presets so we can take advantage and test the global styles font family picking mechanism.
For now, I'm adding just websafe fonts. I think it would be better If we add fonts that "look good" on this theme. cc: @kjellr, @jasmussen, @carolinan, @aristath  in case you have any font suggestions.
=> Add: Font family presets to 2021 blocks.

twentytwentyone-blocks/experimental-theme.json
This PR adds Twenty Twenty-One's gradient presets to `theme.json`. It works just fine except that the gradients themselves aren't showing up in the swatches: 
This is a known Gutenberg problem and is tracked in https://github.com/WordPress/gutenberg/issues/26511. So I don't believe that should hold us back from merging this for now.
=> Twenty Twenty-One Blocks: Add gradient presets

twentytwentyone-blocks/experimental-theme.json
Enables these to show up as labels. 
Before|After
---|---
=> Twenty Twenty-One Blocks: Add color name values to theme.json

twentytwentyone-blocks/assets/css/blocks.css, twentytwentyone-blocks/block-templates/index.html, twentytwentyone-blocks/block-templates/single.html, twentytwentyone-blocks/experimental-theme.json
This PR adds post meta to the footer of posts. For reference, here are the original theme styles for these:
This PR gets somewhat close: 
- It doesn't include any of the text before these, since the blocks don't support that yet. 
- It keeps the post author text in bold, since this is not yet changeable via Gutenberg or global styles. 
---
The PR adds this to the bottom of all single post pages, and also to each post in the main query loop. While I was in there, I made the post titles clickable, which makes this all work way better in general. 😄 
Example of a post in the main index feed:
=> Twenty Twenty-One Blocks: Add post meta. 

twentytwentyone-blocks/assets/css/style-shared.css, twentytwentyone-blocks/experimental-theme.json
This PR: 
- Uses the correct font sizes for the site title and description.
- Brings back the underline for the site title. 
Original Theme|Before|After
---|---|---
(The main remaining difference here is the margin, but I'm not sure how to handle that yet — ideally that would be a Gutenberg setting. That shouldn't block these improvements though.)
=> Twenty Twenty-One Blocks: Use the correct font size + text decoration for the site title and description

twentytwentyone-blocks/assets/css/style-editor.css
This solves (for now) this issue that I filed over here in the Gutenberg repo: https://github.com/WordPress/gutenberg/issues/26630
Basically, the Site Editor does not provide any max-widths out of the box for default and wide blocks. This PR adds them. We'll need this even when a solution for the upstream issue is in place, since we want to define our own widths here. 
Before|After
---|---
=> Twenty Twenty-One Blocks: Add max-widths for alignments in the Site Editor

twentytwentyone-blocks/functions.php
Custom spacing was recently made stable, and it lost the `experimental-` prefix.
=> TwentyTwentyOne blocks: fix custom spacing support

twentytwentyone-blocks/assets/css/blocks.css, twentytwentyone-blocks/experimental-theme.json
This PR should have no effect on the visual appearance. 
When I originally ported over the colors from Twenty Twenty-One, I used some custom color variables in order to keep things straight. I forgot to take those out and use the original preset values instead, but forgot about it until now. 😄
=> Replace custom color variables with preset variables instead

twentytwentyone-blocks/experimental-theme.json
This PR removes the color settings for heading blocks, because it's already set at the global level. There should be no visual change as a result. 
Is there a good reason to set the heading's text color if it's the same as the global context's text color?
=> TT1 blocks: remove redundant color declarations

twentytwentyone-blocks/assets/css/blocks.css, twentytwentyone-blocks/block-templates/404.html
Closes #84.
Adds a basic 404 template, as per the designs. Does not style the search block, pending #82. 
The PR also fixes the display of wide/full separator blocks in the editor.
I can't get this working in the front end (is that a Gutenberg bug?), but I'm seeing it in the site editor:
=> Twenty Twenty-One Blocks: Add 404 Template

README.md, new-empty-theme.php, twentytwentyone-blocks/assets/css/style-shared.css
Using https://github.com/Automattic/underscores.me/blob/master/plugins/underscoresme-generator/underscoresme-generator.php as a reference I created a script that will generate a zip file with a theme based on `emptytheme` that has the name the user gives to the script.
Run `php new-empty-theme.php` from the root of the repo.
We can expand on this to add further info for style.css such as Author, Description, etc. I only did the name as a starting point.
=> Empty Theme: Script to generate a personalized starter theme

.github/workflows/tt1-blocks-staging-deploy.yml
This change adds a GitHub action to deploy the TwentyTwentyOne-Blocks theme to the staging site: https://2021blocks.wordpress.net/ any time code is merged to /master
This gives an up-to-date snapshot of the currently accepted state of the theme.
Prior to bringing this change in the repository should be setup to provide TT1BLOCKS_STAGING_SFTP_USERNAME and TT1BLOCKS_STAGING_SFTP_PASSWORD as GitHub Secrets.
This change should be squash-merged as there is a fair bit of cruft in the commit messages.
=> Deploy TT1-blocks to a staging server when code is merged to master

twentytwentyone-blocks/assets/css/style-shared.css, twentytwentyone-blocks/experimental-theme.json
Added styles for `strong`, `b`, and other tags that affect the paragraph block (and others, of course):
https://github.com/WordPress/twentytwentyone/blob/trunk/assets/sass/04-elements/misc.scss
Related https://github.com/WordPress/theme-experiments/issues/91
=> Twenty Twenty One Blocks: Migrate Paragraph Block styles

emptytheme/assets/alignments-front.css
Our default alignment rules were causing a horizontal scroll on fully aligned images. This PR changes the width value to fix this.
**Before:**
**After:**
=> Empty Theme: Fixed alignfull rule causing a horizontal scroll

emptytheme/experimental-theme.json
This was previously declared under "typography", which is incorrect. 😄 
This PR moves it up a level, so you should see it properly registered and reflected in the UI:
=> Empty Theme: Fix custom spacing entry in theme.json

twentytwentyone-blocks/experimental-theme.json
This PR moves the spacing section up one hierarchy level, as it lives alongside the typography and colors sections.
It also removes the `customUnits`. They aren't different from the defaults, hence are unnecessary.
=> TT1 blocks: move spacing section to proper place

new-empty-theme.php
Previously, themes created using this script would need to have template slug values changed manually for the "stock" content to show up.
This change includes .html files in the change from oldslug > newslug
Tested by creating a new theme using script and loading the theme.  Basic content was showing:
=> Include templates in conversion

new-empty-theme.php
This PR changes the slug used on html templates to be the one using dashes instead of underscores.
Closes https://github.com/WordPress/theme-experiments/issues/146
=> Empty Theme: Changed slug on html templates

tt1-blocks/style.css
This is an attempt to simplify our alignment rules. Since blocks are `display: block` they will already take up 100% width. We only need to add margins when a block is _not_ alignfull.
Why wont this work?
=> TT1 Blocks: Update alignment rules

tt1-blocks/assets/css/blocks.css
The separator block's custom alignment rules are sort of broken. This makes some small adjustments to get them working again. 
Desktop:
- Wide dots separator was misaligned.
Before|After
---|---
Mobile:
- Wide separator went offscreen on the right. 
- Wide dots separator went offscreen too.
Before|After
---|---
=> TT1 Blocks: Update separator alignment rules

tt1-blocks/block-templates/index.html
Fixes https://github.com/WordPress/theme-experiments/issues/158
Adds the query pagination block to index.php.
Updates the query page setting to 100 so that there are pages of results to show 
(It is not possible to select for example  -1 to display all existing results).
=> TT1 Blocks -Add query pagination

tt1-blocks/readme.txt, tt1-blocks/style.css
Since block-based themes can't conform to those `accessibility-ready` standards yet.
_Ref:_ https://themes.trac.wordpress.org/ticket/93906
=> TT1 Blocks: Version bump, remove accessibility-ready tag

tt1-blocks/readme.txt, tt1-blocks/style.css
As per @carolinan's notes [on slack](https://wordpress.slack.com/archives/C02RP4VMP/p1610620845005800): 
> But there are actually other tags that are incorrect as well. footer-widgets, translation-ready are not available in FSE.
> The theme needs to have the full-site-editing tag because it is used to filter the themes in the theme directory.
This PR removes those two tags, and adds the full-site editing tag. 
It also bumps the version number so we can submit this to the theme repo. Rather than do a whole point release, I've changed this to 0.4.1... That way it'll be a while before we hit 1.0. 😄
=> TT1 Blocks: Version bump + update tags

tt1-blocks/readme.txt, tt1-blocks/style.css
The theme description in the repo was pulling from the one in `style.css`, which didn't sync up with the one in the readme.txt. This cleans that up. 
It also changes the release date to today, which is the actual date the theme was released.
=> TT1 Blocks: Fix short theme description and date.

tt1-blocks/style.css
Fixes https://github.com/WordPress/theme-experiments/issues/170
The `max-width` limit here should not override the width of images here, since they should generally be the width of their `figure` or cover containers. 
Separately, we weren't specifying a `max-width` for `alignfull`, which means that they were maxing out at `100%` by default and not taking into account the left/right padding on the container. 
Before
After
=> TT1 Blocks: Fix frontend full alignment styles

tt1-blocks/block-templates/front-page.html
Solves https://github.com/WordPress/theme-experiments/issues/167
=> TT1 Blocks: Delete front-page.html

tt1-blocks/experimental-theme.json
Superseedes https://github.com/WordPress/theme-experiments/pull/175
This PR updates the theme.json to the latest format, according to the two PRs that landed in Gutenberg recently:
- WordPress/gutenberg#28533
- https://github.com/WordPress/gutenberg/pull/28110
How was the format before those PR landed:
```json
{
"global": {
"settings": { ... },
"styles": { ... }
},
"core/paragraph": {
"settings": { ... },
"styles": { ... }
}
}
``` 
How it's now:
```json
{
"settings": {
"defaults": { ... },
"root": { ... },
"core/paragraph": { ... }
},
"styles": {
"root": { ... },
"core/paragraph": { ... }
}
}
```
There's more [details and info in the docs](https://developer.wordpress.org/block-editor/developers/themes/theme-json/).
=> Updates to theme.json

tt1-blocks/experimental-theme.json
:loudspeaker: **The changes have landed in Gutenberg master, so this is ready**
The goal of this PR is to serve as a testbed for the upcoming changes at https://github.com/WordPress/gutenberg/pull/28110
=> Update shape of theme.json: settings & styles as top-level keys

tt1-blocks/block-templates/page-home.html, tt1-blocks/experimental-theme.json
This adds a specific template for the home page, without the page title, so that when its set to be the front page of the site we can hide the title without resorting to CSS.
Follow up to #179
=> TT1 Blocks: Add a static homepage template

tt1-blocks/readme.txt, tt1-blocks/style.css
Now that the `theme.json` format and other template updates have been merged in, I suggest we increase the version number on the theme. 
Once Gutenberg 9.9 is officially published, we can then push this live in the Theme Directory too.
=> TT1 Blocks: Bump the version up to 0.4.3

tt1-blocks/experimental-theme.json
This is minor, but: 
TT1 Blocks [defines a `var(--wp--custom--line-height--page-title)` variable](https://github.com/WordPress/theme-experiments/blob/f181c675b408e18cfcb9266fd475532d67125495/tt1-blocks/experimental-theme.json#L210), but does not use it. This PR changes a `1.1` line height value to that variable instead.
=> TT1 Blocks: Use line height variable for H1

tt1-blocks/block-templates/404.html, tt1-blocks/block-templates/index.html, tt1-blocks/block-templates/page-home.html, tt1-blocks/block-templates/page.html, tt1-blocks/block-templates/single.html
Fixes https://github.com/WordPress/theme-experiments/issues/180
Adds a full width group block with `"tagName":"main"` around the content.
=> TT1 Blocks: Add main element

tt1-blocks/experimental-theme.json
Updates the key used to declared custom templates as per https://github.com/WordPress/gutenberg/pull/28830
=> Rename pageTemplates to customTemplates

gutenberg-starter-theme-blocks/experimental-theme.json, photo-blocks/experimental-theme.json, tt1-blocks/experimental-theme.json, twentytwenty-blocks/experimental-theme.json
Goes along with - https://github.com/WordPress/gutenberg/pull/28410 - to declare the JSON info for template part sections.  This will aid in allowing themes to supply the default taxonomy term used for enabling semantic/categorized template part flows.
=> Block based themes - Add template part section info to theme JSON files.

tt1-blocks/block-templates/index.html, tt1-blocks/block-templates/page-home.html, tt1-blocks/block-templates/page.html, tt1-blocks/block-templates/single.html
On initial creation, the `page-home` template appears to have content that doesn't respect `wide width` or `full width` alignment.
- Spin up the site editor locally
- Activate the tt1-blocks theme
- Navigate to the site editor
- Select the `page-home` template to display
- Find the post content block and click on it
- Verify that the alignment defaults to "full"
=> TT1-Blocks: Fix full width alignment for page-home post content

tt1-blocks/readme.txt, tt1-blocks/style.css
Now that Gutenberg v10.0 is live in the plugin directory, I'd like to package up a new version of TT1 Blocks for submission to the Theme Repo. This PR just bumps the version to make that possible.
(Mostly because https://github.com/WordPress/theme-experiments/pull/202 is required to get the custom homepage template working in 10.0)
=> TT1 Blocks: Bump version to 0.4.4

tt1-blocks/experimental-theme.json
Following up [this change](https://github.com/WordPress/gutenberg/pull/27555) on the editor, this PR removes the font-weight/styles values from theme.json file since they don't work anymore.
Closes #213
=> TT1 blocks: removed font weights/styles from theme.json

emptytheme/style.css
The copyright for this should be to WordPress.org, and I think the theme author should be the WordPress project now, not just me. This PR makes those changes.
=> Empty Theme: Update copyright and author

emptytheme/style.css
It currently points to a LICENSE file that doesn't exist in the theme's directory. Seems simpler to just point to the GPL v2.0 URL.
=> Empty Theme: Update license URI

tt1-blocks/assets/css/blocks.css, tt1-blocks/experimental-theme.json
Now that [this](https://github.com/WordPress/gutenberg/pull/29622) Site Title PR has merged we can express the design of the Site Title block in theme.json:
Fixes https://github.com/WordPress/theme-experiments/issues/163
=> Site Title: Add settings to theme.json

tt1-blocks/experimental-theme.json
Related to changes proposed in Gutenberg in https://github.com/WordPress/gutenberg/pull/29828.
There is going to be a bit different format for `customTemplates` and `templateParts`. The rationale behind it is that we want to align with other lists like font sizes, color palettes, or gradients. It should make it easier to write those configurations but it also will simplify the logic that handles translations.
=> TT1 Blocks: Update custom templates and template parts in the config

tt1-blocks/inc/block-styles.php
TT1 Blocks: Remove the Dark Gray social links block style in favor of color options. Closes #176
=> TT1 Blocks: Remove the Dark Gray social links block style

emptytheme/block-templates/index.html, emptytheme/block-templates/singular.html, emptytheme/functions.php
Removes `"theme":"emptytheme"` from wp:template-part to avoid template part not found messages.
Removes 	`add_theme_support( 'align-wide' );` that is not needed
=> Small clean up for Empty theme

tt1-blocks/assets/css/blocks.css, tt1-blocks/experimental-theme.json
Alternative to #135 and #211, using a custom variable for the font weight for the title blocks.
Since https://github.com/WordPress/gutenberg/pull/29941, neither this PR or #211 relies on https://github.com/WordPress/gutenberg/pull/27639
=> TT1 Blocks Font Weight Value to Headings

tt1-blocks/readme.txt, tt1-blocks/style.css
Update TT1 Blocks to version 4.4.5. This release includes the switch from the theme's own alignments CSS to the new system baked into Gutenberg v10.3. 
Once this is merged, I'll bundle a new release here in the `theme-experiments` repo, and also upload the new version to the theme repository, to correspond with today's [Gutenberg 10.3 release](https://github.com/WordPress/gutenberg/commits/release/10.3).
=> Bump TT1 Blocks to version 4.4.5

README.md
Fixes #248. 
The [Block-based Theme Documentation](https://github.com/WordPress/gutenberg/blob/trunk/docs/how-to-guides/themes/block-based-themes.md) link needs to continue linking to GitHub, because it's still broken in the handbook as per https://github.com/WordPress/gutenberg/issues/25707.
=> Update broken documentation links

emptytheme/experimental-theme.json
Accompanying PR for https://github.com/WordPress/gutenberg/pull/30541
See related PR for TT1-blocks at https://github.com/WordPress/theme-experiments/pull/252
=> Empty theme: use new theme.json shape

tt1-blocks/experimental-theme.json
Accompanying PR for WordPress/gutenberg#30541
See related PR for emptytheme at https://github.com/WordPress/theme-experiments/pull/251
=> TT1-blocks: use new theme.json shape

tt1-blocks/experimental-theme.json
Target:
Before:
After:
Editor:
To test add a button to a page. 
Add another button to a page and set the block style to "outline".
Observe that the styles are (closer to) TwentyTwentyOne button styles.
=> Added theme.json styles for button block to (better) align with TwentyTwentyOne button styles

tt1-blocks/assets/css/blocks.css
The thick separators in TT1 Blocks' templates have been broken for a few releases now. They're supposed to stretch full-width, but instead they appear narrow. This doesn't match up with Twenty Twenty-One. 
There's no specific issue for this, though https://github.com/WordPress/theme-experiments/issues/255 seems similar. This PR fixes this via CSS — this behavior is a custom theme decision, so it feels right to do it in CSS. 
Current|Intended
---|---
=> TT1 Blocks: Make separators 100% wide by default

require-gutenberg/LICENSE, require-gutenberg/README.md, require-gutenberg/require-gutenberg.php
* Adds a license to the script
* Removes code that is no longer necessary since the "experiment" was removed from Gutenberg's options and it is now auto-activated when needed.
=> Update require-gutenberg script & add license

emptytheme/block-templates/index.html
`` is being deprecated, this PR updates it in emptytheme because I was getting a fatal running Gutenberg trunk related to it.
=> emptytheme: use post-template instead of query block

tt1-blocks/block-templates/index.html
This replaces query-loop block usage with post-template block usage (query-loop was deprecated, and is throwing warnings on my tests).
It also updates the query block markup (now it has a `<div class="wp-block-query">`container).
I recommend reviewing the PR without whitespace changes, so it is easier to see what was changed https://github.com/WordPress/theme-experiments/pull/276/files?w=1.
=> Remove query-loop block usage from tt1 blocks. Update query markup.

tt1-blocks/block-templates/index.html
On a fresh install of Gutenberg, running in `wp-env`, I noticed that the current `index.html` template throws an error, due to the `layout` attribute being set to an invalid value (`list`):
This then throws an error in `useAvailableAlignments` [at this line](https://github.com/wordpress/gutenberg/blob/32ecd97e988174b6401289c44200135c224ca104/packages/block-editor/src/components/block-alignment-control/use-available-alignments.js#L34)
This is because the `layout` attribute in this markup should be `displayLayout`, as `layout` is reserved for the Layout block support. The switch to `displayLayout` was introduced in https://github.com/WordPress/gutenberg/pull/31833 (back in May).
It seems that this error occurs because for the current markup the `layout` attribute is being used directly in …
=> TT1-Blocks: Update Query block in index template to use displayLayout instead of layout

emptytheme/theme.json
Emptytheme contains the following code in its theme.json, which is a helpful starting place for theme authors to populate:
```
"color": {
"gradients": [],
"palette": []
},
"typography": {
"fontFamilies": [],
"fontSizes": []
},
```
... but the downside is that this clears out those presets, and makes their associated tools unavailable (as noticed by @jasmussen [here](https://github.com/WordPress/gutenberg/pull/37446#issuecomment-995608534)). 
I think it makes sense to remove them.
=> Emptytheme: Stop clearing presets

tt1-blocks/assets/css/style-shared.css, tt1-blocks/block-template-parts/footer.html, tt1-blocks/block-template-parts/header.html, tt1-blocks/block-templates/404.html, tt1-blocks/block-templates/index.html, tt1-blocks/block-templates/page-home.html, tt1-blocks/block-templates/page.html, tt1-blocks/block-templates/single.html, tt1-blocks/readme.txt, tt1-blocks/theme.json
Fixes #298. 
- Template parts no longer inherit the default layout, so I've moved that into the  templates themselves in the form of an extra group wrapper.
- I've updated the navigation block markup to be in sync with latest versions. 
- I've ported over the left/right padding solution from Twenty Twenty-Two. I don't love this being duplicated in multiple themes, but it's what we've got at the moment. 
cc @kafleg 
Before|After
---|---
=> Fix TT1 Blocks layout issues

tt1-blocks/block-templates/index.html
The query pagination no longer needs a div wrapper, this PR removes it and adds space-between justification to the content.
Before:
After:
=> TT1 Blocks: fixed query pagination markup

tt1-blocks/theme.json
This setting activates block editor-controlled margins for TT1 Blocks. Resolves zeroed margin issue for vertically adjacent blocks in editor.
Also enables additional style control support, [included in WordPress 5.9](https://make.wordpress.org/core/2022/01/08/updates-for-settings-styles-and-theme-json/).
Testing:
- Update tested to resolve display issue (screens above via a4be98961137fbe800d24e2a69d2f846b7a486ff).
- Update tested to confirm `appearanceTools` features remain enabled after removing manual settings (7a41a38d6bad7990ce971c9ba465a14178040a4b).
References:
- https://make.wordpress.org/core/2022/01/08/updates-for-settings-styles-and-theme-json/
Related:
- https://core.trac.wordpress.org/ticket/54250
- https://github.com/WordPress/twentytwentytwo/issues/261
- …
=> Fix T11 Blocks editor block margins and add `appearanceTools` support

CONTRIBUTING.md
This corrects the link to the project's code of conduct.
=> Fix link to Code of Conduct
